


ERRFAIL="ERROR:FAIL"


Buggy=['FIN:AKAFF','FIN:PIGEF','FIN:KNBWF','FIN:KAOCF','FIN:AMDWF',
       'FTE:PSGV','FIN:NCTKF','FRD:H8B3094NSMCAG','FRD:WORAL',
       'FIN:EBCOF','FIN:PORBF','FIN:BDVC','FIN:RYBIF']

